In [1]:
import pandas as pd

titanic = pd.read_csv('titanic.csv')
df_titanic = pd.DataFrame(titanic)
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
import numpy as np

a = np.array([1,2,3,4,5,6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.random.rand(8)*10

array([0.38531022, 6.75344433, 0.5362053 , 2.36080829, 7.09217091,
       9.78073299, 6.8214924 , 6.2714789 ])

In [3]:
import numpy as np

In [16]:
mat = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
mat = mat.reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
mat[2, :] = -7*mat[0, :] + mat[2, :]
mat

array([[  1,   2,   3],
       [  4,   5,   6],
       [  0,  -6, -12]])

In [19]:
mat[2, :] = mat[2, :]/(-6)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2]])

In [20]:
mat[1, :] = mat[1, :] + mat[0, :]*-4
mat

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 0,  1,  2]])

In [21]:
mat[1, :] = mat[1, :]/-3
mat

array([[1, 2, 3],
       [0, 1, 2],
       [0, 1, 2]])

In [22]:
mat[2, :] = mat[2, :] - mat[1, :]
mat

array([[1, 2, 3],
       [0, 1, 2],
       [0, 0, 0]])

In [49]:
mat2 = np.array([1, 0, -3, 8, 2, 2, 9, 7, 0, 1, 5, -2], dtype='float').reshape(3, 4)
mat2

array([[ 1.,  0., -3.,  8.],
       [ 2.,  2.,  9.,  7.],
       [ 0.,  1.,  5., -2.]])

In [50]:
#-2R1 + R2 = R2
mat2[1, :] = mat2[1, :] - 2*mat2[0, :]
mat2

array([[ 1.,  0., -3.,  8.],
       [ 0.,  2., 15., -9.],
       [ 0.,  1.,  5., -2.]])

In [51]:
mat2[2, :] = mat2[2, :]*2 - mat2[1, :]
mat2

array([[ 1.,  0., -3.,  8.],
       [ 0.,  2., 15., -9.],
       [ 0.,  0., -5.,  5.]])

In [52]:
mat2[2, :] = mat2[2, :]/-5
mat2

array([[ 1.,  0., -3.,  8.],
       [ 0.,  2., 15., -9.],
       [-0., -0.,  1., -1.]])

In [53]:
mat2[1, :] = mat2[1, :]/2
mat2

array([[ 1. ,  0. , -3. ,  8. ],
       [ 0. ,  1. ,  7.5, -4.5],
       [-0. , -0. ,  1. , -1. ]])

In [54]:
mat2[0, :] = mat2[0, :] + 3*mat2[2, :]
mat2

array([[ 1. ,  0. ,  0. ,  5. ],
       [ 0. ,  1. ,  7.5, -4.5],
       [-0. , -0. ,  1. , -1. ]])

In [55]:
mat2[1, :] = mat2[1, :] - 7.5*mat2[2, :]
mat2

array([[ 1.,  0.,  0.,  5.],
       [ 0.,  1.,  0.,  3.],
       [-0., -0.,  1., -1.]])

In [56]:
mat3 = np.array([1, -2, -1, 3, 0, -2, 4, 5, -5, 3, 3, -6, -6, 8, 2], dtype='float').reshape(3, 5)
mat3

array([[ 1., -2., -1.,  3.,  0.],
       [-2.,  4.,  5., -5.,  3.],
       [ 3., -6., -6.,  8.,  2.]])

In [58]:
mat3[1, :] = mat3[1, : ] + 2*mat3[0, :]
mat3

array([[ 1., -2., -1.,  3.,  0.],
       [ 0.,  0.,  3.,  1.,  3.],
       [ 3., -6., -6.,  8.,  2.]])

In [59]:
mat3[2, :] = mat3[2, :] - 3*mat3[0, :]
mat3

array([[ 1., -2., -1.,  3.,  0.],
       [ 0.,  0.,  3.,  1.,  3.],
       [ 0.,  0., -3., -1.,  2.]])

In [60]:
mat3[2, :] = mat3[2, :] + mat3[1, :]
mat3

array([[ 1., -2., -1.,  3.,  0.],
       [ 0.,  0.,  3.,  1.,  3.],
       [ 0.,  0.,  0.,  0.,  5.]])

In [62]:
mat4 = np.array([1, 3, 4, 7, 3, 9, 7, 6], dtype='float').reshape(2, 4)
mat4

array([[1., 3., 4., 7.],
       [3., 9., 7., 6.]])

In [63]:
mat4[1, :] = mat4[1, :] - 3*mat4[0, :]
mat4

array([[  1.,   3.,   4.,   7.],
       [  0.,   0.,  -5., -15.]])

In [64]:
mat4[1, :] = mat4[1, :]/-5
mat4

array([[ 1.,  3.,  4.,  7.],
       [-0., -0.,  1.,  3.]])

In [65]:
mat4[0, :] = mat4[0, :] - 4*mat4[1, :]
mat4

array([[ 1.,  3.,  0., -5.],
       [-0., -0.,  1.,  3.]])